/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import static java.lang.Double.parseDouble;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import modeldatabase.Connector;
import model.ModelMovie;
import controller.Control;

/**
 *
 * @author Lisa Meliana
 */
public class ViewMovie extends javax.swing.JFrame {
    static Connector DB;
    Control movie;
    
    /** Creates new form MovieView */
    public ViewMovie(Connector DB) {
        initComponents();
        this.DB = DB;
        this.movie = new Control(new Movie(DB));
        DefaultTableModel model = (DefaultTableModel)this.tbl_movie.getModel();
        Object[] row = new Object[5];
        model.setRowCount(0);
        for (int i = 0; movie.index()[i][0] != null; i++) {
            row[0] = movie.index()[i][0];
            row[1] = movie.index()[i][1];
            row[2] = movie.index()[i][2];
            row[3] = movie.index()[i][3];
            row[4] = movie.index()[i][4];
            model.addRow(row);
        }
    }

    private ViewMovie() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_movie = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        tx_judul = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        tx_alur = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        tx_penokohan = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        tx_akting = new javax.swing.JTextField();
        btn_tambah = new javax.swing.JButton();
        btn_update = new javax.swing.JButton();
        btn_delete = new javax.swing.JButton();
        btn_clear = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tbl_movie.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Judul", "Alur", "Penokohan", "Akting", "Nilai"
            }
        ));
        jScrollPane1.setViewportView(tbl_movie);

        jLabel1.setText("Judul");

        jLabel2.setText("Alur");

        jLabel3.setText("Penokohan");

        jLabel4.setText("Akting");

        tx_akting.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tx_aktingActionPerformed(evt);
            }
        });

        btn_tambah.setText("Tambah");
        btn_tambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_tambahActionPerformed(evt);
            }
        });

        btn_update.setText("Update");

        btn_delete.setText("Delete");

        btn_clear.setText("Clear");

        org.jdesktop.layout.GroupLayout layout;
        layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(jScrollPane1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(54, 54, 54)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING, false)
                    .add(tx_judul)
                    .add(jLabel2)
                    .add(jLabel3)
                    .add(jLabel4)
                    .add(tx_alur)
                    .add(tx_penokohan)
                    .add(tx_akting, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 156, Short.MAX_VALUE)
                    .add(jLabel1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 37, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING, false)
                        .add(org.jdesktop.layout.GroupLayout.LEADING, btn_clear, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .add(org.jdesktop.layout.GroupLayout.LEADING, btn_delete, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .add(org.jdesktop.layout.GroupLayout.LEADING, btn_update, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .add(org.jdesktop.layout.GroupLayout.LEADING, btn_tambah, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 104, Short.MAX_VALUE)))
                .addContainerGap(46, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .add(jScrollPane1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .add(layout.createSequentialGroup()
                .add(29, 29, 29)
                .add(jLabel1)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(tx_judul, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                .add(jLabel2)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(tx_alur, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                .add(jLabel3)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(tx_penokohan, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                .add(jLabel4)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(tx_akting, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(37, 37, 37)
                .add(btn_tambah)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                .add(btn_update)
                .add(11, 11, 11)
                .add(btn_delete)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                .add(btn_clear)
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_tambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_tambahActionPerformed
        // TODO add your handling code here:
         try{
            String judul = tx_judul.getText();
            double alur = parseDouble(tx_alur.getText());
            double penokohan= parseDouble(tx_penokohan.getText());
            double akting = parseDouble(tx_akting.getText());

            movie.store(judul, alur, penokohan, akting);
        }catch(Exception err){
            JOptionPane.showMessageDialog(null,"Lengkapi Semua Kolom!");
        }
        
        DefaultTableModel model = (DefaultTableModel)this.tbl_movie.getModel();
        Object[] row = new Object[5];
        model.setRowCount(0);
        for (int i = 0; movie.index()[i][0] != null; i++) {
            row[0] = movie.index()[i][0];
            row[1] = movie.index()[i][1];
            row[2] = movie.index()[i][2];
            row[3] = movie.index()[i][3];
            row[4] = movie.index()[i][4];
            model.addRow(row);
        }
        this.tx_judul.setText("");
        this.tx_alur.setText("");
        this.tx_penokohan.setText("");
        this.tx_akting.setText("");
    }//GEN-LAST:event_btn_tambahActionPerformed
     private void tbl_movieMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        // TODO add your handling code here:
        DefaultTableModel model = (DefaultTableModel)this.tbl_movie.getModel();
        Object title = model.getValueAt(this.tbl_movie.getSelectedRow(), 0);
        Object story = model.getValueAt(this.tbl_movie.getSelectedRow(), 1);
        Object actors = model.getValueAt(this.tbl_movie.getSelectedRow(), 2);
        Object acting = model.getValueAt(this.tbl_movie.getSelectedRow(), 3);

        this.tx_judul.setText(title.toString());
        this.tx_alur.setText(story.toString());
        this.tx_penokohan.setText(actors.toString());
        this.tx_akting.setText(acting.toString());

    }//GEN-LAST:event_jTable1MouseClicked

    private void btn_updateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        try{
            String judul = tx_judul.getText();
            double alur = parseDouble(tx_alur.getText());
            double penokohan= parseDouble(tx_penokohan.getText());
            double akting = parseDouble(tx_akting.getText());

            movie.update(judul, alur, penokohan, akting);
        }catch(Exception err){
            JOptionPane.showMessageDialog(null,"Lengkapi Semua Kolom!");
        }
        DefaultTableModel model = (DefaultTableModel)this.tbl_movie.getModel();
        Object[] row = new Object[5];
        model.setRowCount(0);
        for (int i = 0; movie.index()[i][0] != null; i++) {
            row[0] = movie.index()[i][0];
            row[1] = movie.index()[i][1];
            row[2] = movie.index()[i][2];
            row[3] = movie.index()[i][3];
            row[4] = movie.index()[i][4];
            model.addRow(row);
        }
        this.tx_judul.setText("");
        this.tx_alur.setText("");
        this.tx_penokohan.setText("");
        this.tx_akting.setText("");
    }//GEN-LAST:event_jButton2ActionPerformed

    private void btn_clearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        this.tx_judul.setText("");
        this.tx_alur.setText("");
        this.tx_penokohan.setText("");
        this.tx_akting.setText("");
    }//GEN-LAST:event_jButton4ActionPerformed

    private void btn_deleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        try{
            String judul = tx_judul.getText();
            movie.delete(judul);
        }catch(Exception err){
            JOptionPane.showMessageDialog(null,"Movie Tidak ditemukan!");
        }
        
        DefaultTableModel model = (DefaultTableModel)this.tbl_movie.getModel();
        Object[] row = new Object[5];
        model.setRowCount(0);
        for (int i = 0; movie.index()[i][0] != null; i++) {
            row[0] = movie.index()[i][0];
            row[1] = movie.index()[i][1];
            row[2] = movie.index()[i][2];
            row[3] = movie.index()[i][3];
            row[4] = movie.index()[i][4];
            model.addRow(row);
        }
        this.tx_judul.setText("");
        this.tx_alur.setText("");
        this.tx_penokohan.setText("");
        this.tx_akting.setText("");
    }//GEN-LAST:event_jButton3ActionPerformed
    
    private void tx_aktingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tx_aktingActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tx_aktingActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ViewMovie.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ViewMovie.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ViewMovie.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ViewMovie.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ViewMovie().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_clear;
    private javax.swing.JButton btn_delete;
    private javax.swing.JButton btn_tambah;
    private javax.swing.JButton btn_update;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tbl_movie;
    private javax.swing.JTextField tx_akting;
    private javax.swing.JTextField tx_alur;
    private javax.swing.JTextField tx_judul;
    private javax.swing.JTextField tx_penokohan;
    // End of variables declaration//GEN-END:variables

    private static class Movie extends ModelMovie {

        public Movie(Connector DB) {
        }
    }

}
